# root直下のdocsで編集あったらこのタスクも実行
syncdocs:
	cp ../../docs/index.html ./docs/
	cp ../../docs/main.css ./docs/
	cp ../../docs/main.js ./docs/
	cp ../../docs/main.wasm ./docs/
	cp ../../docs/wasm_exec.js ./docs/
